spring:
  application:
    name: springcloud-service-center

# 端口号
server:
  port: 50000

# Eureka Server 配置
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:${server.port}/eureka/